/* ELEA's service-aware booking flow. Loaded after app.js on pages with a booking modal. */
(function () {
  'use strict';
  const services = [
    'HOME CLEANING / HOUSEKEEPING', 'OVEN & APPLIANCE CLEANING', 'WINDOW CLEANING',
    'HOME ORGANIZATION', 'MOVE-IN / MOVE-OUT CLEANING', 'AFTER-RENOVATION CLEANING', 'DUSTBIN / BIN CLEANING'
  ];
  const extras = ['DUSTBIN / BIN CLEANING', 'WINDOW CLEANING', 'OVEN & APPLIANCE CLEANING', 'HOME ORGANIZATION'];
  const photoServices = new Set(services.slice(1));
  const timeOptions = Array.from({ length: 24 }, (_, hour) => `${String(hour).padStart(2, '0')}:00`);
  const berlinLocations = ['Adlershof','Alt-Hohenschönhausen','Alt-Treptow','Altglienicke','Baumschulenweg','Biesdorf','Blankenburg','Bohnsdorf','Borsigwalde','Borsigwalde','Borsigwalde','Britz','Buch','Buckow','Charlottenburg','Charlottenburg-Nord','Dahlem','Falkenberg','Falkenhagener Feld','Fennpfuhl','Friedenau','Friedrichsfelde','Friedrichshagen','Friedrichshain','Gatow','Gesundbrunnen','Gropiusstadt','Grunewald','Grünau','Hakenfelde','Halensee','Hansaviertel','Haselhorst','Heiligensee','Heinersdorf','Hellersdorf','Hermsdorf','Hessenwinkel','Johannisthal','Kaulsdorf','Karow','Karlshorst','Kladow','Köpenick','Konradshöhe','Kreuzberg','Lankwitz','Lichtenberg','Lichterfelde','Lübars','Mahlsdorf','Malchow','Mariendorf','Marienfelde','Märkisches Viertel','Marzahn','Mitte','Moabit','Müggelheim','Neukölln','Niederschöneweide','Niederschönhausen','Nikolaiviertel','Nikolassee','Oberschöneweide','Pankow','Plänterwald','Prenzlauer Berg','Rahnsdorf','Reinickendorf','Rosenthal','Rudow','Rummelsburg','Schmargendorf','Schmöckwitz','Schöneberg','Siemensstadt','Spandau','Staaken','Stadtrandsiedlung Malchow','Staaken','Steglitz','Tegel','Tempelhof','Tiergarten','Treptow','Waidmannslust','Wannsee','Wartenberg','Wedding','Weißensee','Westend','Wilhelmstadt','Wilhelmsruh','Wilmersdorf','Wittenau','Zehlendorf'].filter((value, index, list) => list.indexOf(value) === index).sort();
  const esc = (v) => String(v || '').replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
  const label = (key) => ({ bedrooms: 'Bedrooms', bathrooms: 'Bathrooms', kitchens: 'Kitchens', livingRooms: 'Living rooms', propertySize: 'Approximate property size', balconies: 'Are there balconies?', balconyCount: 'How many balconies?' }[key] || key);
  const field = (key, text, type = 'text', value = '') => `<label class="booking-field"><span>${text}</span><input class="elea-input" data-bf="${key}" type="${type}" value="${esc(value)}"></label>`;
  const select = (key, text, options, value = '') => `<label class="booking-field"><span>${text}</span><select class="elea-input" data-bf="${key}"><option value="">Select</option>${options.map(o => `<option value="${esc(o)}" ${value === o ? 'selected' : ''}>${esc(o)}</option>`).join('')}</select></label>`;
  const textarea = (key, text, value = '') => `<label class="booking-field booking-field-full"><span>${text}</span><textarea class="elea-input" data-bf="${key}">${esc(value)}</textarea></label>`;
  const comboboxInput = (key, text, value, type, options = '') => `<label class="booking-field booking-combobox"><span>${text}</span><input class="elea-input" data-bf="${key}" ${type === 'street' ? 'data-street-search' : 'data-location-search'} value="${esc(value)}" autocomplete="off" aria-autocomplete="list" aria-expanded="true"><div class="booking-address-dropdown" data-address-dropdown="${type}">${options}</div></label>`;
  const choices = (key, text, options, state, multiple = false) => `<fieldset class="booking-section-card booking-choice-field"><legend>${text}</legend><div class="booking-option-grid">${options.map(o => { const on = multiple ? (state[key] || []).includes(o) : state[key] === o; return `<label class="booking-choice ${on ? 'active' : ''}"><input data-bf="${key}" type="${multiple ? 'checkbox' : 'radio'}" name="${key}" value="${esc(o)}" ${on ? 'checked' : ''}><span>${esc(o)}</span></label>`; }).join('')}</div></fieldset>`;
  const dateTime = (s) => `<section class="booking-section-card"><h3>Preferred date & time</h3><div class="booking-two-col">${field('_date', 'Preferred date', 'date', s.date)}${select('_time', 'Preferred time (24-hour format)', timeOptions, s.time)}</div></section>`;
  const photo = (s, suffix = '') => photoServices.has(s.service) || s.additionalServices.some(x => photoServices.has(x)) ? `<label class="booking-field booking-field-full"><span>Photos${suffix ? ` of ${suffix}` : ''} (optional)</span><input class="elea-input" data-photos type="file" accept="image/*" multiple><small>${s.photoFiles.length ? `${s.photoFiles.length} photo(s) selected` : 'Photos help Elea provide a more accurate quote.'}</small></label>` : '';
  const useGerman = () => typeof getLang === 'function' ? getLang() !== 'en' : document.documentElement.lang !== 'en';
  const germanText = {
    'Select': 'Bitte wählen', 'Preferred date & time': 'Wunschdatum & Wunschzeit', 'Preferred date': 'Wunschdatum', 'Preferred time (24-hour format)': 'Wunschzeit (24-Stunden-Format)',
    'Photos (optional)': 'Fotos (optional)', 'Special requests / additional information': 'Besondere Wünsche / zusätzliche Informationen', 'Continue': 'Weiter', 'Back': 'Zurück', 'Submit request': 'Anfrage vorbereiten',
    'Choose your main service': 'Wählen Sie Ihre Hauptleistung', 'Select one service. We’ll only show the questions relevant to it.': 'Wählen Sie eine Leistung. Wir zeigen nur die dazu passenden Fragen.',
    'Not sure what you need? Request a quote and tell us about the work.': 'Nicht sicher, was Sie benötigen? Fordern Sie ein Angebot an und beschreiben Sie die Arbeit.',
    'Your details': 'Ihre Kontaktdaten', 'Full name': 'Vollständiger Name', 'Phone': 'Telefon', 'Email': 'E-Mail', 'Street': 'Straße', 'Location / neighbourhood': 'Ort / Kiez', 'Postal code': 'Postleitzahl', 'House number / address line': 'Hausnummer / Adresszusatz',
    'Start typing a Berlin street to see matching addresses, or enter your own details.': 'Beginnen Sie mit der Eingabe einer Berliner Straße, um passende Adressen zu sehen, oder geben Sie Ihre Daten selbst ein.',
    'Choose WhatsApp or email on the next screen to send your request to Elea.': 'Wählen Sie auf der nächsten Seite WhatsApp oder E-Mail, um Ihre Anfrage an Elea zu senden.',
    'Choose how to send your request': 'Wählen Sie, wie Sie Ihre Anfrage senden möchten', 'Your request has not been sent to Elea yet. Choose WhatsApp or email below, then send the pre-filled message to complete your request.': 'Ihre Anfrage wurde noch nicht an Elea gesendet. Wählen Sie unten WhatsApp oder E-Mail und senden Sie anschließend die vorausgefüllte Nachricht.',
    'Choose WhatsApp': 'WhatsApp wählen', 'Choose Email': 'E-Mail wählen', 'Reference': 'Referenz', 'Service': 'Leistung', 'Details': 'Details', 'Contact': 'Kontakt',
    'What type of cleaning do you need?': 'Welche Art Reinigung benötigen Sie?', 'Regular Cleaning': 'Regelmäßige Reinigung', 'Deep Cleaning': 'Grundreinigung', 'Property information': 'Angaben zur Immobilie', 'Bedrooms': 'Schlafzimmer', 'Bathrooms': 'Badezimmer', 'Kitchens': 'Küchen', 'Living rooms': 'Wohnzimmer', 'Approximate property size (optional)': 'Ungefähre Wohnfläche (optional)',
    'Additional areas': 'Zusätzliche Bereiche', 'Additional services': 'Zusatzleistungen', 'Hallway': 'Flur', 'Balcony': 'Balkon', 'Office': 'Büro', 'Storage room': 'Abstellraum', 'Basement': 'Keller', 'Other': 'Andere',
    'Select appliance(s)': 'Gerät(e) auswählen', 'How many appliances?': 'Wie viele Geräte?', 'What cleaning is required?': 'Welche Reinigung wird benötigt?', 'Appliance condition': 'Zustand der Geräte', 'Inside': 'Innen', 'Outside': 'Außen', 'Inside + Outside': 'Innen + Außen', 'Light dirt': 'Leichte Verschmutzung', 'Heavy dirt': 'Starke Verschmutzung', 'Grease buildup': 'Fettablagerungen', 'Burnt-on food': 'Eingebrannte Rückstände', 'Limescale': 'Kalkablagerungen',
    'Approximately how many windows?': 'Ungefähr wie viele Fenster?', 'What type of windows?': 'Welche Art Fenster?', 'Standard windows': 'Standardfenster', 'Large windows': 'Große Fenster', 'Floor-to-ceiling windows': 'Bodentiefe Fenster', 'Glass doors': 'Glastüren', 'Are the windows easily accessible?': 'Sind die Fenster leicht zugänglich?', 'Any difficult or high windows?': 'Gibt es schwer zugängliche oder hohe Fenster?', 'Include frames and sills?': 'Rahmen und Fensterbänke einschließen?', 'Yes': 'Ja', 'No': 'Nein',
    'Which area needs organization?': 'Welcher Bereich soll organisiert werden?', 'What type of organization do you need?': 'Welche Art Organisation benötigen Sie?', 'Approximate size of the area': 'Ungefähre Größe des Bereichs', 'Help deciding what to do?': 'Hilfe bei der Entscheidung?', 'Is there a large amount of clutter?': 'Gibt es viel Unordnung?', 'Need storage/organization solutions?': 'Werden Aufbewahrungs- oder Organisationslösungen benötigt?',
    'Is this:': 'Handelt es sich um:', 'Move-In Cleaning': 'Einzugsreinigung', 'Move-Out Cleaning': 'Auszugsreinigung', 'Is the property furnished or empty?': 'Ist die Immobilie möbliert oder leer?', 'Are there balconies?': 'Gibt es Balkone?', 'How many balconies?': 'Wie viele Balkone?', 'Which are required?': 'Was wird benötigt?', 'Condition of property': 'Zustand der Immobilie',
    'What type of renovation was completed?': 'Welche Renovierung wurde durchgeführt?', 'Number of rooms': 'Anzahl der Räume', 'Condition / renovation residue': 'Zustand / Renovierungsrückstände', 'How many bins need cleaning?': 'Wie viele Tonnen sollen gereinigt werden?', 'What type of bins?': 'Welche Art Tonnen?', 'Where are the bins located?': 'Wo befinden sich die Tonnen?', 'What condition are the bins in?': 'In welchem Zustand sind die Tonnen?', 'What service do they need?': 'Welche Leistung wird benötigt?'
  };
  function translateBookingUi(root) {
    if (!useGerman()) return;
    const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT);
    const nodes = []; while (walker.nextNode()) nodes.push(walker.currentNode);
    nodes.forEach((node) => { const value = node.nodeValue.trim(); if (germanText[value]) node.nodeValue = node.nodeValue.replace(value, germanText[value]); });
  }

  function scope(service, s, prefix = '', includeSchedule = true) {
    if (prefix) includeSchedule = false;
    const f = s.form, k = (name) => prefix + name, v = (name) => f[k(name)] || '';
    const common = () => `${includeSchedule ? dateTime(s) : ''}${textarea(k('specialInstructions'), 'Special requests / additional information', v('specialInstructions'))}${includeSchedule ? photo(s) : ''}`;
    if (service === 'HOME CLEANING / HOUSEKEEPING') return `${choices(k('cleaningType'), 'What type of cleaning do you need?', ['Regular Cleaning', 'Deep Cleaning'], f)}<section class="booking-section-card"><h3>Property information</h3><div class="booking-two-col">${['bedrooms','bathrooms','kitchens','livingRooms'].map(x => field(k(x), label(x), 'number', v(x))).join('')}${field(k('propertySize'), 'Approximate property size (optional)', 'text', v('propertySize'))}</div></section>${choices(k('additionalAreas'), 'Additional areas', ['Hallway','Balcony','Office','Storage room','Basement','Other'], f, true)}${common()}`;
    if (service === 'OVEN & APPLIANCE CLEANING') return `${choices(k('appliances'), 'Select appliance(s)', ['Oven','Stove / Cooktop','Extractor Hood','Refrigerator / Freezer','Dishwasher','Washing Machine','Dryer','Microwave','Other'], f, true)}<div class="booking-two-col">${field(k('applianceCount'), 'How many appliances?', 'number', v('applianceCount'))}${select(k('applianceCleaningType'), 'What cleaning is required?', ['Inside','Outside','Inside + Outside'], v('applianceCleaningType'))}${select(k('applianceCondition'), 'Appliance condition', ['Light dirt','Heavy dirt','Grease buildup','Burnt-on food','Limescale','Other'], v('applianceCondition'))}</div>${common()}`;
    if (service === 'WINDOW CLEANING') return `<div class="booking-two-col">${field(k('windowsCount'), 'Approximately how many windows?', 'number', v('windowsCount'))}${select(k('windowType'), 'What type of windows?', ['Standard windows','Large windows','Floor-to-ceiling windows','Glass doors','Other'], v('windowType'))}${select(k('windowCleaningType'), 'What cleaning is required?', ['Inside','Outside','Inside + Outside'], v('windowCleaningType'))}${select(k('windowsAccessible'), 'Are the windows easily accessible?', ['Yes','No'], v('windowsAccessible'))}${select(k('windowsDifficult'), 'Any difficult or high windows?', ['Yes','No'], v('windowsDifficult'))}${select(k('windowsHeavyDirt'), 'Heavy dirt, dust, grease, paint or buildup?', ['Yes','No','Other / describe'], v('windowsHeavyDirt'))}${select(k('windowFramesSills'), 'Include frames and sills?', ['Yes','No'], v('windowFramesSills'))}</div>${common()}`;
    if (service === 'HOME ORGANIZATION') { const wardrobe = (f[k('organizationArea')] || []).includes('Wardrobe / Closet') && v('organizationType') === 'Wardrobe organization'; return `${choices(k('organizationArea'), 'Which area needs organization?', ['Bedroom','Wardrobe / Closet','Kitchen','Living Room','Bathroom','Storage Room','Office',"Children's Room",'Basement','Other'], f, true)}${choices(k('organizationType'), 'What type of organization do you need?', ['Decluttering','Sorting','Wardrobe organization','Kitchen organization','Storage organization','General home organization','Other'], f)}<div class="booking-two-col">${field(k('organizationSize'), 'Approximate size of the area', 'text', v('organizationSize'))}${select(k('organizationHelp'), 'Help deciding what to do?', ['Keep','Donate','Discard','Organize'], v('organizationHelp'))}${select(k('clutter'), 'Is there a large amount of clutter?', ['Yes','No'], v('clutter'))}${select(k('storageSolutions'), 'Need storage/organization solutions?', ['Yes','No'], v('storageSolutions'))}</div>${wardrobe ? `<section class="booking-section-card"><h3>Wardrobe organization at your home</h3>${choices(k('wardrobeHelp'), 'What would you like help with?', ['Wardrobe organization','Folding clothes','Ironing clothes','Folding + Ironing','Full wardrobe organization + Folding + Ironing'], f)}<div class="booking-two-col">${field(k('wardrobeItems'), 'Approximate clothes/items to fold or iron', 'number', v('wardrobeItems'))}${field(k('delicateClothes'), 'Delicate or special-care clothes?', 'text', v('delicateClothes'))}</div>${textarea(k('foldingPreferences'), 'Folding or arrangement preferences', v('foldingPreferences'))}<p class="booking-note">Elea provides folding, ironing and wardrobe organization in your home. You provide the clothes, wardrobe and any ironing equipment.</p></section>` : ''}${common()}`; }
    if (service === 'MOVE-IN / MOVE-OUT CLEANING') return `${choices(k('moveType'), 'Is this:', ['Move-In Cleaning','Move-Out Cleaning'], f)}<section class="booking-section-card"><h3>Property information</h3><div class="booking-two-col">${['bedrooms','bathrooms','kitchens','livingRooms'].map(x => field(k(x), label(x), 'number', v(x))).join('')}${field(k('propertySize'), 'Approximate property size', 'text', v('propertySize'))}${select(k('furnished'), 'Is the property furnished or empty?', ['Furnished','Empty'], v('furnished'))}${select(k('balconies'), 'Are there balconies?', ['Yes','No'], v('balconies'))}${v('balconies') === 'Yes' ? field(k('balconyCount'), 'How many balconies?', 'number', v('balconyCount')) : ''}</div></section>${choices(k('moveTasks'), 'Which are required?', ['Window cleaning','Oven cleaning','Appliance cleaning','Inside cupboards/cabinets','Inside wardrobes','Inside refrigerator/freezer','Other'], f, true)}${choices(k('propertyCondition'), 'Condition of property', ['Light dirt','Heavy dirt','Grease','Limescale','Dust','Stains','Other'], f, true)}${common()}`;
    if (service === 'AFTER-RENOVATION CLEANING') return `${choices(k('renovationType'), 'What type of renovation was completed?', ['Kitchen renovation','Bathroom renovation','Flooring','Painting','Full renovation','Other'], f)}<section class="booking-section-card"><h3>Property information</h3><div class="booking-two-col">${field(k('renovationRooms'), 'Number of rooms', 'number', v('renovationRooms'))}${['bedrooms','bathrooms','kitchens','livingRooms'].map(x => field(k(x), label(x), 'number', v(x))).join('')}${field(k('propertySize'), 'Approximate property size', 'text', v('propertySize'))}${select(k('balconies'), 'Are there balconies?', ['Yes','No'], v('balconies'))}${v('balconies') === 'Yes' ? field(k('balconyCount'), 'How many balconies?', 'number', v('balconyCount')) : ''}</div></section>${choices(k('renovationResidue'), 'Condition / renovation residue', ['Construction dust','Fine dust','Paint residue','Plaster residue','Cement residue','Glue / adhesive residue','Silicone residue','Dirt on floors','Dust on windows','Other renovation residue'], f, true)}${choices(k('renovationTasks'), 'Which are required?', ['Window cleaning','Oven / appliance cleaning','Inside cupboards/cabinets','Floor cleaning','Detailed surface cleaning','Other'], f, true)}${common()}`;
    return `<div class="booking-two-col">${field(k('binCount'), 'How many bins need cleaning?', 'number', v('binCount'))}${choices(k('binTypes'), 'What type of bins?', ['General waste','Recycling','Organic waste','Other'], f, true)}${select(k('binLocation'), 'Where are the bins located?', ['Inside','Outside','Both'], v('binLocation'))}${select(k('binCondition'), 'What condition are the bins in?', ['Light dirt','Heavy dirt','Food residue','Bad smell','Grease','Other'], v('binCondition'))}${select(k('binService'), 'What service do they need?', ['Cleaning only','Cleaning + disinfection/deodorizing'], v('binService'))}</div>${common()}`;
  }
  function relevantServices(s) { return s.service ? [s.service, ...s.additionalServices] : []; }
  function isValid(s) { if (!s.service && !s.quote) return 'Please choose a main service or request a quote.'; if (!s.date || !s.time) return 'Please choose a preferred date and time.'; if (!s.customer.name || !s.customer.phone || !s.customer.email || !/^\S+@\S+\.\S+$/.test(s.customer.email)) return 'Please enter your name, phone number and a valid email address.'; const f=s.form; if (s.service === 'HOME CLEANING / HOUSEKEEPING' && !f.cleaningType) return 'Please choose a cleaning type.'; if (s.service === 'OVEN & APPLIANCE CLEANING' && (!(f.appliances||[]).length || !f.applianceCount || !f.applianceCleaningType || !f.applianceCondition)) return 'Please complete the appliance details.'; if (s.service === 'WINDOW CLEANING' && (!f.windowsCount || !f.windowType || !f.windowCleaningType)) return 'Please complete the window details.'; if (s.service === 'HOME ORGANIZATION' && (!(f.organizationArea||[]).length || !f.organizationType)) return 'Please choose the area and type of organization.'; if (s.service === 'MOVE-IN / MOVE-OUT CLEANING' && !f.moveType) return 'Please choose move-in or move-out cleaning.'; if (s.service === 'AFTER-RENOVATION CLEANING' && !f.renovationType) return 'Please choose the renovation type.'; if (s.service === 'DUSTBIN / BIN CLEANING' && (!f.binCount || !(f.binTypes||[]).length || !f.binLocation || !f.binCondition || !f.binService)) return 'Please complete the bin details.'; return ''; }
  function summary(s) { const rows = [['Service', s.service || 'Quote request / unsure of exact work'], ['Additional services', s.additionalServices.join(', ')], ...Object.entries(s.form).filter(([,v]) => Array.isArray(v) ? v.length : v).map(([k,v]) => [k.replace(/([A-Z])/g, ' $1'), Array.isArray(v) ? v.join(', ') : v]), ['Preferred date',s.date], ['Preferred time',s.time], ['Full name',s.customer.name], ['Phone',s.customer.phone], ['Email',s.customer.email], ['Address',[s.customer.street,s.customer.postalCode,s.customer.location,s.customer.address].filter(Boolean).join(', ')], ['Special requests',s.customer.notes]].filter(([,v])=>v); return rows; }
  function message(s) { return `ELEA BOOKING REQUEST\n\n${summary(s).map(([k,v])=>`${k}: ${v}`).join('\n')}${s.photoUrls.length ? `\n\nPhotos:\n${s.photoUrls.join('\n')}` : ''}`; }
  async function persist(s) { const urls=[]; if (window.eleaSupabase) for (const file of s.photoFiles) { const key=`bookings/${s.reference}/${Date.now()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`; const upload=await window.eleaSupabase.uploadFile(key,file); if (!upload.error) urls.push(upload.data?.publicUrl || (await window.eleaSupabase.getPublicUrl(key)).data?.publicUrl); } s.photoUrls=urls.filter(Boolean); const record={reference_code:s.reference,customer_name:s.customer.name,customer_email:s.customer.email,customer_phone:s.customer.phone,service_types:relevantServices(s),preferred_date:s.date,preferred_time:s.time,notes:JSON.stringify({quote_request:s.quote,details:s.form,address:s.customer,photo_names:s.photoFiles.map(x=>x.name)}),booking_details:{quote_request:s.quote,details:s.form,address:s.customer},booking_images:s.photoUrls.map(url=>({public_url:url,storage_path:url}))}; const res=await window.eleaSupabase.createBooking(record); if(res?.error) console.warn('Booking storage unavailable:',res.error.message); }
  function render() { const modal=document.getElementById('booking-modal'), s=modal?.bookingState; if(!modal||!s)return; setTimeout(() => translateBookingUi(modal), 0); if(s.done){const msg=message(s); modal.innerHTML=`<header class="booking-header"><div class="elea-container booking-header-inner"><div class="booking-title">ELEA</div><button class="booking-close" data-close aria-label="Close">×</button></div></header><div class="elea-container booking-body"><div class="booking-success"><div class="success-icon">→</div><h2 class="elea-heading">Choose how to send your request</h2><p>Your request has not been sent to Elea yet. Choose WhatsApp or email below, then send the pre-filled message to complete your request.</p><div class="success-reference-box"><div class="eyebrow">Reference</div><div class="success-reference">${s.reference}</div></div><div class="success-actions"><a class="elea-button-primary" target="_blank" rel="noreferrer" href="https://wa.me/${window.defaults?.whatsappNumber || '4915216019843'}?text=${encodeURIComponent(msg)}">Choose WhatsApp</a><a class="elea-button-outline" href="mailto:${window.defaults?.email || 'eleacleaning@gmail.com'}?subject=${encodeURIComponent(`ELEA booking ${s.reference}`)}&body=${encodeURIComponent(msg)}">Choose Email</a></div></div></div>`; modal.querySelector('[data-close]').onclick=close; return; }
    const locationOptions = berlinLocations.map((location) => `<option value="${esc(location)}"></option>`).join('');
    const streetOptions = (s.streetMatches || []).map((match) => `<option value="${esc(match.label)}"></option>`).join('');
    const content=s.step===0?`<h2 class="elea-heading booking-step-question">Choose your main service</h2><p class="booking-step-hint">Select one service. We’ll only show the questions relevant to it.</p><div class="booking-service-grid">${services.map(x=>`<button type="button" class="booking-toggle ${s.service===x?'active':''}" data-service="${x}"><span class="toggle-title">${x}</span></button>`).join('')}</div><button type="button" class="booking-toggle quote-toggle ${s.quote?'active':''}" data-quote><span class="toggle-title">Not sure what you need? Request a quote and tell us about the work.</span></button>`:s.step===1?`${s.quote&&!s.service?textarea('quoteDescription','Tell us about the work',s.form.quoteDescription):scope(s.service,s)}${s.service==='HOME CLEANING / HOUSEKEEPING'?choices('additionalServices','Optional additional services',extras,s,true):''}${s.additionalServices.map(x=>`<section class="booking-extra"><h3>${x}</h3>${scope(x,s,`extra_${x.slice(0,3).toLowerCase()}_`)}</section>`).join('')}`:`<h2 class="elea-heading booking-step-question">Your details</h2><p class="booking-step-hint">Start typing a Berlin street to see matching addresses, or enter your own details.</p><div class="booking-two-col">${field('_name','Full name','text',s.customer.name)}${field('_phone','Phone','tel',s.customer.phone)}${field('_email','Email','email',s.customer.email)}${datalistInput('_street','Street',s.customer.street,'berlin-street-options',streetOptions,true)}${datalistInput('_location','Location / neighbourhood',s.customer.location,'berlin-location-options',locationOptions)}${field('_postalCode','Postal code','text',s.customer.postalCode)}${field('_address','House number / address line','text',s.customer.address)}</div>${textarea('_notes','Special requests / additional information',s.customer.notes)}<p class="booking-confirmation">Choose WhatsApp or email on the next screen to send your request to Elea.</p>`;
    modal.innerHTML=`<header class="booking-header"><div class="elea-container booking-header-inner"><div class="booking-title">ELEA</div><button class="booking-close" data-close aria-label="Close">×</button></div></header><div class="elea-container booking-body"><div class="booking-step-labels"><span class="${s.step===0?'active':''}">01 Service</span><span class="${s.step===1?'active':''}">02 Details</span><span class="${s.step===2?'active':''}">03 Contact</span></div><div class="booking-step-panel booking-form-stack">${content}</div><div class="booking-actions"><button class="booking-back ${s.step?'':'disabled'}" ${s.step?'':'disabled'} data-back>Back</button><button class="booking-submit-button" data-next>${s.step===2?'Submit request':'Continue'}</button></div><div class="booking-error ${s.error?'show':''}">${s.error||''}</div></div>`;
    modal.querySelector('[data-close]').onclick=close; modal.querySelector('[data-back]')?.addEventListener('click',()=>{s.step--;s.error='';render();}); modal.querySelector('[data-quote]')?.addEventListener('click',()=>{s.quote=!s.quote;if(s.quote)s.service='';render();}); modal.querySelectorAll('[data-service]').forEach(b=>b.onclick=()=>{s.service=b.dataset.service;s.quote=false;s.additionalServices=[];s.form={};render();}); modal.querySelectorAll('[data-bf]').forEach(el=>el.addEventListener('change',()=>{const k=el.dataset.bf;if(k==='_date')s.date=el.value;else if(k==='_time')s.time=el.value;else if(k.startsWith('_'))s.customer[k.slice(1)]=el.value;else if(el.type==='checkbox'){const vals=[...modal.querySelectorAll(`[data-bf="${k}"]:checked`)].map(x=>x.value);s.form[k]=vals;if(k==='additionalServices')s.additionalServices=vals;render();}else{s.form[k]=el.value;if(k==='balconies'||k.endsWith('_balconies')||k==='organizationType')render();}})); modal.querySelector('[data-photos]')?.addEventListener('change',e=>{s.photoFiles=[...e.target.files].filter(f=>f.type.startsWith('image/')&&f.size<=10*1024*1024); if(s.photoFiles.length!==e.target.files.length)s.error='Only image files up to 10 MB can be uploaded.';}); modal.querySelector('[data-next]').onclick=async()=>{if(s.step<2){if(s.step===0&& !s.service&&!s.quote){s.error='Please choose a main service or request a quote.';render();return;}s.step++;s.error='';render();return;}s.error=isValid(s);if(s.error){render();return;}s.submitting=true;try{s.reference=`EL-${Math.random().toString(36).slice(2,6).toUpperCase()}`;await persist(s);s.done=true;}catch(e){console.error(e);s.error='We could not save the request. Please try again or contact Elea via WhatsApp.';}render();};
  }
  let streetSearchTimer;
  document.addEventListener('input', (event) => {
    const input = event.target;
    if (!input.matches?.('[data-street-search]')) return;
    const modal = document.getElementById('booking-modal');
    const state = modal?.bookingState;
    if (!state) return;
    state.customer.street = input.value;
    clearTimeout(streetSearchTimer);
    if (input.value.trim().length < 3) return;
    streetSearchTimer = setTimeout(async () => {
      try {
        const query = encodeURIComponent(`${input.value.trim()}, Berlin`);
        const response = await fetch(`https://photon.komoot.io/api/?q=${query}&lat=52.52&lon=13.405&limit=12&lang=en`);
        const payload = await response.json();
        state.streetMatches = (payload.features || []).map(({ properties = {} }) => {
          const street = properties.street || properties.name || '';
          const houseNumber = properties.housenumber || '';
          const postalCode = properties.postcode || '';
          const location = properties.district || properties.locality || properties.city || '';
          return { street, houseNumber, postalCode, location, label: [street, houseNumber].filter(Boolean).join(' ') + (postalCode ? `, ${postalCode} Berlin` : '') + (location ? ` — ${location}` : '') };
        }).filter((match) => match.street && match.label);
        const list = document.getElementById('berlin-street-options');
        if (list) list.innerHTML = state.streetMatches.map((match) => `<option value="${esc(match.label)}"></option>`).join('');
      } catch (error) { console.warn('Berlin address suggestions are unavailable:', error); }
    }, 260);
  });
  document.addEventListener('change', (event) => {
    const input = event.target;
    if (!input.matches?.('[data-street-search]')) return;
    const state = document.getElementById('booking-modal')?.bookingState;
    const match = state?.streetMatches?.find((item) => item.label === input.value);
    if (!match) return;
    state.customer.street = match.street;
    state.customer.postalCode = match.postalCode || state.customer.postalCode;
    state.customer.location = match.location || state.customer.location;
    if (!state.customer.address && match.houseNumber) state.customer.address = match.houseNumber;
    const modal = document.getElementById('booking-modal');
    const postalCode = modal?.querySelector('[data-bf="_postalCode"]');
    const location = modal?.querySelector('[data-bf="_location"]');
    const address = modal?.querySelector('[data-bf="_address"]');
    if (postalCode) postalCode.value = state.customer.postalCode;
    if (location) location.value = state.customer.location;
    if (address) address.value = state.customer.address;
  });
  function close(){const m=document.getElementById('booking-modal');if(m){m.classList.remove('open');document.body.style.overflow='';}}
  window.openBookingModal=function(service=''){const modal=document.getElementById('booking-modal');if(!modal)return; const normalized=services.includes(service)?service:(typeof normalizeServiceKey==='function'?normalizeServiceKey(service):'');modal.bookingState={step:0,service:services.includes(normalized)?normalized:'',quote:false,additionalServices:[],form:{},date:'',time:'',customer:{name:'',phone:'',email:'',street:'',postalCode:'',location:'',address:'',notes:''},streetMatches:[],photoFiles:[],photoUrls:[],error:'',done:false,reference:''};modal.classList.add('open');document.body.style.overflow='hidden';render();};
  window.renderBookingModal = render;
  window.closeBookingModal=close;
}());
