/* ELEA's service-aware booking flow. Loaded after app.js on pages with a booking modal. */
(function () {
  'use strict';
  const services = [
    'HOME CLEANING / HOUSEKEEPING', 'OVEN & APPLIANCE CLEANING', 'WINDOW CLEANING',
    'HOME ORGANIZATION', 'MOVE-IN / MOVE-OUT CLEANING', 'AFTER-RENOVATION CLEANING', 'DUSTBIN / BIN CLEANING'
  ];
  const extras = ['DUSTBIN / BIN CLEANING', 'WINDOW CLEANING', 'OVEN & APPLIANCE CLEANING', 'HOME ORGANIZATION'];
  const photoServices = new Set(services.slice(1));
  const esc = (v) => String(v || '').replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
  const label = (key) => ({ bedrooms: 'Bedrooms', bathrooms: 'Bathrooms', kitchens: 'Kitchens', livingRooms: 'Living rooms', propertySize: 'Approximate property size', balconies: 'Are there balconies?', balconyCount: 'How many balconies?' }[key] || key);
  const field = (key, text, type = 'text', value = '') => `<label class="booking-field"><span>${text}</span><input class="elea-input" data-bf="${key}" type="${type}" value="${esc(value)}"></label>`;
  const select = (key, text, options, value = '') => `<label class="booking-field"><span>${text}</span><select class="elea-input" data-bf="${key}"><option value="">Select</option>${options.map(o => `<option value="${esc(o)}" ${value === o ? 'selected' : ''}>${esc(o)}</option>`).join('')}</select></label>`;
  const textarea = (key, text, value = '') => `<label class="booking-field booking-field-full"><span>${text}</span><textarea class="elea-input" data-bf="${key}">${esc(value)}</textarea></label>`;
  const choices = (key, text, options, state, multiple = false) => `<fieldset class="booking-section-card booking-choice-field"><legend>${text}</legend><div class="booking-option-grid">${options.map(o => { const on = multiple ? (state[key] || []).includes(o) : state[key] === o; return `<label class="booking-choice ${on ? 'active' : ''}"><input data-bf="${key}" type="${multiple ? 'checkbox' : 'radio'}" name="${key}" value="${esc(o)}" ${on ? 'checked' : ''}><span>${esc(o)}</span></label>`; }).join('')}</div></fieldset>`;
  const dateTime = (s) => `<section class="booking-section-card"><h3>Preferred date & time</h3><div class="booking-two-col">${field('_date', 'Preferred date', 'date', s.date)}${field('_time', 'Preferred time', 'time', s.time)}</div></section>`;
  const photo = (s, suffix = '') => photoServices.has(s.service) || s.additionalServices.some(x => photoServices.has(x)) ? `<label class="booking-field booking-field-full"><span>Photos${suffix ? ` of ${suffix}` : ''} (optional)</span><input class="elea-input" data-photos type="file" accept="image/*" multiple><small>${s.photoFiles.length ? `${s.photoFiles.length} photo(s) selected` : 'Photos help Elea provide a more accurate quote.'}</small></label>` : '';

  function scope(service, s, prefix = '', includeSchedule = true) {
    if (prefix) includeSchedule = false;
    const f = s.form, k = (name) => prefix + name, v = (name) => f[k(name)] || '';
    const common = () => `${includeSchedule ? dateTime(s) : ''}${textarea(k('specialInstructions'), 'Special requests / additional information', v('specialInstructions'))}${includeSchedule ? photo(s) : ''}`;
    if (service === 'HOME CLEANING / HOUSEKEEPING') return `${choices(k('cleaningType'), 'What type of cleaning do you need?', ['Regular Cleaning', 'Deep Cleaning'], f)}<section class="booking-section-card"><h3>Property information</h3><div class="booking-two-col">${['bedrooms','bathrooms','kitchens','livingRooms'].map(x => field(k(x), label(x), 'number', v(x))).join('')}${field(k('propertySize'), 'Approximate property size (optional)', 'text', v('propertySize'))}</div></section>${choices(k('additionalAreas'), 'Additional areas', ['Hallway','Balcony','Office','Storage room','Basement','Other'], f, true)}${common()}`;
    if (service === 'OVEN & APPLIANCE CLEANING') return `${choices(k('appliances'), 'Select appliance(s)', ['Oven','Stove / Cooktop','Extractor Hood','Refrigerator / Freezer','Dishwasher','Washing Machine','Dryer','Microwave','Other'], f, true)}<div class="booking-two-col">${field(k('applianceCount'), 'How many appliances?', 'number', v('applianceCount'))}${select(k('applianceCleaningType'), 'What cleaning is required?', ['Inside','Outside','Inside + Outside'], v('applianceCleaningType'))}${select(k('applianceCondition'), 'Appliance condition', ['Light dirt','Heavy dirt','Grease buildup','Burnt-on food','Limescale','Other'], v('applianceCondition'))}</div>${common()}`;
    if (service === 'WINDOW CLEANING') return `<div class="booking-two-col">${field(k('windowsCount'), 'Approximately how many windows?', 'number', v('windowsCount'))}${select(k('windowType'), 'What type of windows?', ['Standard windows','Large windows','Floor-to-ceiling windows','Glass doors','Other'], v('windowType'))}${select(k('windowCleaningType'), 'What cleaning is required?', ['Inside','Outside','Inside + Outside'], v('windowCleaningType'))}${select(k('windowsAccessible'), 'Are the windows easily accessible?', ['Yes','No'], v('windowsAccessible'))}${select(k('windowsDifficult'), 'Any difficult or high windows?', ['Yes','No'], v('windowsDifficult'))}${select(k('windowsHeavyDirt'), 'Heavy dirt, dust, grease, paint or buildup?', ['Yes','No','Other / describe'], v('windowsHeavyDirt'))}${select(k('windowFramesSills'), 'Include frames and sills?', ['Yes','No'], v('windowFramesSills'))}</div>${common()}`;
    if (service === 'HOME ORGANIZATION') { const wardrobe = (f[k('organizationArea')] || []).includes('Wardrobe / Closet') && v('organizationType') === 'Wardrobe organization'; return `${choices(k('organizationArea'), 'Which area needs organization?', ['Bedroom','Wardrobe / Closet','Kitchen','Living Room','Bathroom','Storage Room','Office',"Children's Room",'Basement','Other'], f, true)}${choices(k('organizationType'), 'What type of organization do you need?', ['Decluttering','Sorting','Wardrobe organization','Kitchen organization','Storage organization','General home organization','Other'], f)}<div class="booking-two-col">${field(k('organizationSize'), 'Approximate size of the area', 'text', v('organizationSize'))}${select(k('organizationHelp'), 'Help deciding what to do?', ['Keep','Donate','Discard','Organize'], v('organizationHelp'))}${select(k('clutter'), 'Is there a large amount of clutter?', ['Yes','No'], v('clutter'))}${select(k('storageSolutions'), 'Need storage/organization solutions?', ['Yes','No'], v('storageSolutions'))}</div>${wardrobe ? `<section class="booking-section-card"><h3>Wardrobe organization at your home</h3>${choices(k('wardrobeHelp'), 'What would you like help with?', ['Wardrobe organization','Folding clothes','Ironing clothes','Folding + Ironing','Full wardrobe organization + Folding + Ironing'], f)}<div class="booking-two-col">${field(k('wardrobeItems'), 'Approximate clothes/items to fold or iron', 'number', v('wardrobeItems'))}${field(k('delicateClothes'), 'Delicate or special-care clothes?', 'text', v('delicateClothes'))}</div>${textarea(k('foldingPreferences'), 'Folding or arrangement preferences', v('foldingPreferences'))}<p class="booking-note">Elea provides folding, ironing and wardrobe organization in your home. You provide the clothes, wardrobe and any ironing equipment.</p></section>` : ''}${common()}`; }
    if (service === 'MOVE-IN / MOVE-OUT CLEANING') return `${choices(k('moveType'), 'Is this:', ['Move-In Cleaning','Move-Out Cleaning'], f)}<section class="booking-section-card"><h3>Property information</h3><div class="booking-two-col">${['bedrooms','bathrooms','kitchens','livingRooms'].map(x => field(k(x), label(x), 'number', v(x))).join('')}${field(k('propertySize'), 'Approximate property size', 'text', v('propertySize'))}${select(k('furnished'), 'Is the property furnished or empty?', ['Furnished','Empty'], v('furnished'))}${select(k('balconies'), 'Are there balconies?', ['Yes','No'], v('balconies'))}${v('balconies') === 'Yes' ? field(k('balconyCount'), 'How many balconies?', 'number', v('balconyCount')) : ''}</div></section>${choices(k('moveTasks'), 'Which are required?', ['Window cleaning','Oven cleaning','Appliance cleaning','Inside cupboards/cabinets','Inside wardrobes','Inside refrigerator/freezer','Other'], f, true)}${choices(k('propertyCondition'), 'Condition of property', ['Light dirt','Heavy dirt','Grease','Limescale','Dust','Stains','Other'], f, true)}${common()}`;
    if (service === 'AFTER-RENOVATION CLEANING') return `${choices(k('renovationType'), 'What type of renovation was completed?', ['Kitchen renovation','Bathroom renovation','Flooring','Painting','Full renovation','Other'], f)}<section class="booking-section-card"><h3>Property information</h3><div class="booking-two-col">${field(k('renovationRooms'), 'Number of rooms', 'number', v('renovationRooms'))}${['bedrooms','bathrooms','kitchens','livingRooms'].map(x => field(k(x), label(x), 'number', v(x))).join('')}${field(k('propertySize'), 'Approximate property size', 'text', v('propertySize'))}${select(k('balconies'), 'Are there balconies?', ['Yes','No'], v('balconies'))}${v('balconies') === 'Yes' ? field(k('balconyCount'), 'How many balconies?', 'number', v('balconyCount')) : ''}</div></section>${choices(k('renovationResidue'), 'Condition / renovation residue', ['Construction dust','Fine dust','Paint residue','Plaster residue','Cement residue','Glue / adhesive residue','Silicone residue','Dirt on floors','Dust on windows','Other renovation residue'], f, true)}${choices(k('renovationTasks'), 'Which are required?', ['Window cleaning','Oven / appliance cleaning','Inside cupboards/cabinets','Floor cleaning','Detailed surface cleaning','Other'], f, true)}${common()}`;
    return `<div class="booking-two-col">${field(k('binCount'), 'How many bins need cleaning?', 'number', v('binCount'))}${choices(k('binTypes'), 'What type of bins?', ['General waste','Recycling','Organic waste','Other'], f, true)}${select(k('binLocation'), 'Where are the bins located?', ['Inside','Outside','Both'], v('binLocation'))}${select(k('binCondition'), 'What condition are the bins in?', ['Light dirt','Heavy dirt','Food residue','Bad smell','Grease','Other'], v('binCondition'))}${select(k('binService'), 'What service do they need?', ['Cleaning only','Cleaning + disinfection/deodorizing'], v('binService'))}</div>${common()}`;
  }
  function relevantServices(s) { return s.service ? [s.service, ...s.additionalServices] : []; }
  function isValid(s) { if (!s.service && !s.quote) return 'Please choose a main service or request a quote.'; if (!s.date || !s.time) return 'Please choose a preferred date and time.'; if (!s.customer.name || !s.customer.phone || !s.customer.email || !/^\S+@\S+\.\S+$/.test(s.customer.email)) return 'Please enter your name, phone number and a valid email address.'; const f=s.form; if (s.service === 'HOME CLEANING / HOUSEKEEPING' && !f.cleaningType) return 'Please choose a cleaning type.'; if (s.service === 'OVEN & APPLIANCE CLEANING' && (!(f.appliances||[]).length || !f.applianceCount || !f.applianceCleaningType || !f.applianceCondition)) return 'Please complete the appliance details.'; if (s.service === 'WINDOW CLEANING' && (!f.windowsCount || !f.windowType || !f.windowCleaningType)) return 'Please complete the window details.'; if (s.service === 'HOME ORGANIZATION' && (!(f.organizationArea||[]).length || !f.organizationType)) return 'Please choose the area and type of organization.'; if (s.service === 'MOVE-IN / MOVE-OUT CLEANING' && !f.moveType) return 'Please choose move-in or move-out cleaning.'; if (s.service === 'AFTER-RENOVATION CLEANING' && !f.renovationType) return 'Please choose the renovation type.'; if (s.service === 'DUSTBIN / BIN CLEANING' && (!f.binCount || !(f.binTypes||[]).length || !f.binLocation || !f.binCondition || !f.binService)) return 'Please complete the bin details.'; return ''; }
  function summary(s) { const rows = [['Service', s.service || 'Quote request / unsure of exact work'], ['Additional services', s.additionalServices.join(', ')], ...Object.entries(s.form).filter(([,v]) => Array.isArray(v) ? v.length : v).map(([k,v]) => [k.replace(/([A-Z])/g, ' $1'), Array.isArray(v) ? v.join(', ') : v]), ['Preferred date',s.date], ['Preferred time',s.time], ['Full name',s.customer.name], ['Phone',s.customer.phone], ['Email',s.customer.email], ['Address',[s.customer.street,s.customer.location,s.customer.address].filter(Boolean).join(', ')], ['Special requests',s.customer.notes]].filter(([,v])=>v); return rows; }
  function message(s) { return `ELEA BOOKING REQUEST\n\n${summary(s).map(([k,v])=>`${k}: ${v}`).join('\n')}${s.photoUrls.length ? `\n\nPhotos:\n${s.photoUrls.join('\n')}` : ''}`; }
  async function persist(s) { const urls=[]; if (window.eleaSupabase) for (const file of s.photoFiles) { const key=`bookings/${s.reference}/${Date.now()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`; const upload=await window.eleaSupabase.uploadFile(key,file); if (!upload.error) urls.push(upload.data?.publicUrl || (await window.eleaSupabase.getPublicUrl(key)).data?.publicUrl); } s.photoUrls=urls.filter(Boolean); const record={reference_code:s.reference,customer_name:s.customer.name,customer_email:s.customer.email,customer_phone:s.customer.phone,service_types:relevantServices(s),preferred_date:s.date,preferred_time:s.time,notes:JSON.stringify({quote_request:s.quote,details:s.form,address:s.customer,photo_names:s.photoFiles.map(x=>x.name)}),booking_details:{quote_request:s.quote,details:s.form,address:s.customer},booking_images:s.photoUrls.map(url=>({public_url:url,storage_path:url}))}; const res=await window.eleaSupabase.createBooking(record); if(res?.error) console.warn('Booking storage unavailable:',res.error.message); }
  function render() { const modal=document.getElementById('booking-modal'), s=modal?.bookingState; if(!modal||!s)return; if(s.done){const msg=message(s); modal.innerHTML=`<header class="booking-header"><div class="elea-container booking-header-inner"><div class="booking-title">ELEA</div><button class="booking-close" data-close aria-label="Close">×</button></div></header><div class="elea-container booking-body"><div class="booking-success"><div class="success-icon">✓</div><h2 class="elea-heading">Request received</h2><p>Your appointment is not automatically confirmed. Elea will review your request, provide the price/quote, and confirm your appointment.</p><div class="success-reference-box"><div class="eyebrow">Reference</div><div class="success-reference">${s.reference}</div></div><div class="success-actions"><a class="elea-button-primary" target="_blank" rel="noreferrer" href="https://wa.me/${window.defaults?.whatsappNumber || '4915216019843'}?text=${encodeURIComponent(msg)}">Send via WhatsApp</a><a class="elea-button-outline" href="mailto:${window.defaults?.email || 'eleacleaning@gmail.com'}?subject=${encodeURIComponent(`ELEA booking ${s.reference}`)}&body=${encodeURIComponent(msg)}">Send via Email</a></div></div></div>`; modal.querySelector('[data-close]').onclick=close; return; }
    const content=s.step===0?`<h2 class="elea-heading booking-step-question">Choose your main service</h2><p class="booking-step-hint">Select one service. We’ll only show the questions relevant to it.</p><div class="booking-service-grid">${services.map(x=>`<button type="button" class="booking-toggle ${s.service===x?'active':''}" data-service="${x}"><span class="toggle-title">${x}</span></button>`).join('')}</div><button type="button" class="booking-toggle quote-toggle ${s.quote?'active':''}" data-quote><span class="toggle-title">Not sure what you need? Request a quote and tell us about the work.</span></button>`:s.step===1?`${s.quote&&!s.service?textarea('quoteDescription','Tell us about the work',s.form.quoteDescription):scope(s.service,s)}${s.service==='HOME CLEANING / HOUSEKEEPING'?choices('additionalServices','Optional additional services',extras,s,true):''}${s.additionalServices.map(x=>`<section class="booking-extra"><h3>${x}</h3>${scope(x,s,`extra_${x.slice(0,3).toLowerCase()}_`)}</section>`).join('')}`:`<h2 class="elea-heading booking-step-question">Your details</h2><div class="booking-two-col">${field('_name','Full name','text',s.customer.name)}${field('_phone','Phone','tel',s.customer.phone)}${field('_email','Email','email',s.customer.email)}${field('_street','Street','text',s.customer.street)}${field('_location','Location','text',s.customer.location)}${field('_address','Address','text',s.customer.address)}</div>${textarea('_notes','Special requests / additional information',s.customer.notes)}<p class="booking-confirmation">Submitting this request does not automatically confirm your appointment. Elea will review it and respond with your price/quote and appointment confirmation.</p>`;
    modal.innerHTML=`<header class="booking-header"><div class="elea-container booking-header-inner"><div class="booking-title">ELEA</div><button class="booking-close" data-close aria-label="Close">×</button></div></header><div class="elea-container booking-body"><div class="booking-step-labels"><span class="${s.step===0?'active':''}">01 Service</span><span class="${s.step===1?'active':''}">02 Details</span><span class="${s.step===2?'active':''}">03 Contact</span></div><div class="booking-step-panel booking-form-stack">${content}</div><div class="booking-actions"><button class="booking-back ${s.step?'':'disabled'}" ${s.step?'':'disabled'} data-back>Back</button><button class="booking-submit-button" data-next>${s.step===2?'Submit request':'Continue'}</button></div><div class="booking-error ${s.error?'show':''}">${s.error||''}</div></div>`;
    modal.querySelector('[data-close]').onclick=close; modal.querySelector('[data-back]')?.addEventListener('click',()=>{s.step--;s.error='';render();}); modal.querySelector('[data-quote]')?.addEventListener('click',()=>{s.quote=!s.quote;if(s.quote)s.service='';render();}); modal.querySelectorAll('[data-service]').forEach(b=>b.onclick=()=>{s.service=b.dataset.service;s.quote=false;s.additionalServices=[];s.form={};render();}); modal.querySelectorAll('[data-bf]').forEach(el=>el.addEventListener('change',()=>{const k=el.dataset.bf;if(k==='_date')s.date=el.value;else if(k==='_time')s.time=el.value;else if(k.startsWith('_'))s.customer[k.slice(1)]=el.value;else if(el.type==='checkbox'){const vals=[...modal.querySelectorAll(`[data-bf="${k}"]:checked`)].map(x=>x.value);s.form[k]=vals;if(k==='additionalServices')s.additionalServices=vals;render();}else{s.form[k]=el.value;if(k==='balconies'||k.endsWith('_balconies')||k==='organizationType')render();}})); modal.querySelector('[data-photos]')?.addEventListener('change',e=>{s.photoFiles=[...e.target.files].filter(f=>f.type.startsWith('image/')&&f.size<=10*1024*1024); if(s.photoFiles.length!==e.target.files.length)s.error='Only image files up to 10 MB can be uploaded.';}); modal.querySelector('[data-next]').onclick=async()=>{if(s.step<2){if(s.step===0&& !s.service&&!s.quote){s.error='Please choose a main service or request a quote.';render();return;}s.step++;s.error='';render();return;}s.error=isValid(s);if(s.error){render();return;}s.submitting=true;try{s.reference=`EL-${Math.random().toString(36).slice(2,6).toUpperCase()}`;await persist(s);s.done=true;}catch(e){console.error(e);s.error='We could not save the request. Please try again or contact Elea via WhatsApp.';}render();};
  }
  function close(){const m=document.getElementById('booking-modal');if(m){m.classList.remove('open');document.body.style.overflow='';}}
  window.openBookingModal=function(service=''){const modal=document.getElementById('booking-modal');if(!modal)return; const normalized=services.includes(service)?service:(typeof normalizeServiceKey==='function'?normalizeServiceKey(service):'');modal.bookingState={step:0,service:services.includes(normalized)?normalized:'',quote:false,additionalServices:[],form:{},date:'',time:'',customer:{name:'',phone:'',email:'',street:'',location:'',address:'',notes:''},photoFiles:[],photoUrls:[],error:'',done:false,reference:''};modal.classList.add('open');document.body.style.overflow='hidden';render();};
  window.closeBookingModal=close;
}());
